spring:
  datasource:
    driveClassName: commysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/forum
    username: root
    password: root

  jpa:
    defer-datasource-initialization: false
    database-plataform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  h2:
    console:
      enable: true

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: f8c99b268ca473
    password: 24da9618461484
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: secreto





